### ISSUE TITLE
documentation: installation instructions

### ISSUE THREAD

**Issue by jamesdalg** [polly-code/lammps_le#1]
Perhaps I'm missing it, but the readme does not seem to contain installation instructions. Can you signpost me to the correct file? I'm familiar with how to install optional packages with LAMMPS, but not 3rd party packages like this that aren't stored in the same folder as the cloned lammps repository.

**Comment by polly-code** [comment]
Hi @jamesdalg, I have added an installation section to the readme. In this repo, you will find a full LAMMPS, so please install it as usual. The module is provided as an additional package, `USER-LE`. Please, let me know if it helps.

**Comment by jamesdalg** [comment]
Thanks! that's a huge help. Is there a tutorial that is unique to your package?

**Comment by polly-code** [comment]
You are welcome! More detailed description you can find in the preprint:
https://www.biorxiv.org/content/10.1101/2022.03.03.482826v1.full
I plan to push it to the main LAMMPS repo. I will suggest a page with a tutorial there. But it's not a top priority.

**Comment by jamesdalg** [comment]
Thanks! LAMMPS really needs better documentation (I haven't been able to find a single text with LAMMPS code that isn't the manual for writing LAMMPS extentions). Whatever you can do to make it accessible will get it noticed more and could be helpful in gaining citations and possibly acceptance in a publication, at least that was my experience in my last software-based paper.

**Comment by jamesdalg** [comment]
I'll read the paper too! Thanks for pointing it out.
